import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, LockKeyhole } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

export default function Login() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const { login, loading } = useAuth(); const navigate = useNavigate();
  const submit = async (e) => { e.preventDefault(); setError(''); const result = await login(email, password); if (result.success) navigate('/dashboard'); else setError(result.message); };
  return <div className="auth-page"><div className="auth-visual"><div className="brand"><span className="brand-mark">C</span> CogniLab</div><div className="auth-quote"><span className="eyebrow">Research operations</span><h1>Make every response count.</h1><p>Build precise browser-based studies and understand the quality behind every measurement.</p></div><div className="auth-foot">Timing-aware research, built for the web.</div></div><main className="auth-panel"><div className="auth-form"><div className="auth-mobile-brand brand"><span className="brand-mark">C</span> CogniLab</div><span className="eyebrow">Researcher access</span><h2>Welcome back</h2><p className="muted">Sign in to manage your experiments.</p>{error && <div className="error">{error}</div>}<form onSubmit={submit}><div className="field"><label>Email address</label><input autoFocus required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@lab.org" /></div><div className="field"><label>Password</label><input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Enter your password" /></div><button className="btn btn-primary auth-submit" disabled={loading}>{loading ? 'Signing in...' : 'Sign in'} {!loading && <ArrowRight size={16} />}</button></form><p className="auth-switch">New to CogniLab? <Link to="/register">Create a researcher account</Link></p><div className="auth-note"><LockKeyhole size={15} /> Your workspace is protected with secure authentication.</div></div></main></div>;
}
