import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

export default function Register() {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const { register, loading } = useAuth(); const navigate = useNavigate();
  const submit = async (e) => { e.preventDefault(); setError(''); const result = await register(name, email, password); if (result.success) navigate('/dashboard'); else setError(result.message); };
  return <div className="auth-page"><div className="auth-visual"><div className="brand"><span className="brand-mark">C</span> CogniLab</div><div className="auth-quote"><span className="eyebrow">Your next study</span><h1>From hypothesis to insight.</h1><p>Configure experiments, capture raw timing, and keep environmental reliability in view.</p></div><div className="auth-foot">A clearer workspace for behavioral research.</div></div><main className="auth-panel"><div className="auth-form"><div className="auth-mobile-brand brand"><span className="brand-mark">C</span> CogniLab</div><span className="eyebrow">Researcher access</span><h2>Create your workspace</h2><p className="muted">Set up your account and start designing a study.</p>{error && <div className="error">{error}</div>}<form onSubmit={submit}><div className="field"><label>Full name</label><input autoFocus required value={name} onChange={(e) => setName(e.target.value)} placeholder="Dr. Alex Vance" /></div><div className="field"><label>Email address</label><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@lab.org" /></div><div className="field"><label>Password <span className="field-hint">At least 6 characters</span></label><input required minLength={6} type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Create a password" /></div><button className="btn btn-primary auth-submit" disabled={loading}>{loading ? 'Creating workspace...' : 'Create workspace'} {!loading && <ArrowRight size={16} />}</button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></div></main></div>;
}
